---
author:
  email: colibri.alex@gmail.com
  name: "Alex Gil"
  url: "https://twitter.com/elotroalex"
baseurl: /vol1
collections:
  texts:
    output: true
color-scheme: ~
description: "Ed is a Jekyll theme designed for textual editors based on minimal computing principles, and focused on legibility and flexibility."
encoding: utf-8
exclude:
  - optional
  - vendor
kramdown:
  auto_ids: true
  enable_coderay: false
  entity_output: as_char
  footnote_backlink: "↩︎"
  footnote_nr: 1
  smart_quotes: "lsquo,rsquo,ldquo,rdquo"
  toc_levels: "1..6"
markdown: kramdown
permalink: "/:title/"
tagline: "an online digital edition of Marx's CAPITAL"
theme: ed.
title: Vol. 1
url: "http://minicomp.github.io"
