---
author:
  email: marxist-reading@andrew.cmu.edu
  name: "Steven Gotzler"
  url: "https://twitter.com/cmrg_cmu"
#baseurl: /MARXdown
collections:
  texts:
    output: true
color-scheme: ~
description: "MARXdown is an online digital project developed for the Contemporary Marxist Reading Group (CMRG) at Carnegie Mellon University using the lightweight markup language Markdown."
encoding: utf-8
exclude:
  - optional
  - vendor
kramdown:
  auto_ids: true
  enable_coderay: false
  entity_output: as_char
  footnote_backlink: "↩︎"
  footnote_nr: 1
  smart_quotes: "lsquo,rsquo,ldquo,rdquo"
  toc_levels: "1..6"
markdown: kramdown
permalink: "/:title/"
tagline: "(Ed. + hypothes.is)"
theme: ed.
title: MARXdown
url: https://MARXdown.github.io
