---
author:
  email: marxist-reading@andrew.cmu.edu
  name: "Steven Gotzler"
  url: "https://twitter.com/cmrg_cmu"
#baseurl: /MARXdown
collections:
  texts:
    output: true
color-scheme: ~
description: ""There is no royal road to science, and only those who do not dread the fatiguing climb of its steep paths have a chance of gaining its luminous summits.” —Karl Marx, Capital Vol. 1, Preface to the French Edition (1872)"
encoding: utf-8
exclude:
  - optional
  - vendor
kramdown:
  auto_ids: true
  enable_coderay: false
  entity_output: as_char
  footnote_backlink: "↩︎"
  footnote_nr: 1
  smart_quotes: "lsquo,rsquo,ldquo,rdquo"
  toc_levels: "1..6"
markdown: kramdown
permalink: "/:title/"
tagline: "(Ed. + hypothes.is)"
title: MARXdown
url: https://MARXdown.github.io
defaults:
  - scope:
      type: texts
    values:
      editor: Steven Gotzler, Avery J. Wiscomb, and Daniel J. Evans
